### PR TITLE
Stylesheet conforms to ExpressibleByArrayLiteral

### PR DESCRIPTION
**Pull request by gmosx**
This small changes allows you to change

```
let css: Stylesheet =
      body % (
        background(Color.red)
          <> (a & .pseudo(.firstChild)) % (
            color(.blue)
        )
    )
    <> (ul ** li) % (
      color(.red)
        <> (.pseudo(.firstChild)) & (
          color(.blue)
      )
    )
    <> input % (
      outlineStyle(all: .none)
        <> outlineWidth(all: 0)
        <> outlineColor(all: .transparent)
    )
    <> input["type"=="submit"] % (
      boxShadow(stroke: .inset, hShadow: .px(1), vShadow: .px(1), color: .rgba(0, 0, 0, 1))
        <> appearance(.button)
    )
```

into 

```
let css: Stylesheet = [
    body % [
        background(Color.red),
        (a & .pseudo(.firstChild)) % (
            color(.blue)
        )
    ],
    (ul ** li) % [
      color(.red),
      (.pseudo(.firstChild)) & (
        color(.blue)
      )
    ],
    input % [
      outlineStyle(all: .none),
      outlineWidth(all: 0),
      outlineColor(all: .transparent)
    ],
    input["type"=="submit"] % [
      boxShadow(stroke: .inset, hShadow: .px(1), vShadow: .px(1), color: .rgba(0, 0, 0, 1)),
      appearance(.button)
    ]
]
```

I think the later is more **readable** and more consistent with regard to the Html EDSL.

What do you think?

### CODE REVIEW

**Comment by gmosx** [comment]
So, guys, what do you think about this change?

**Comment by stephencelis** [comment]
Hey @gmosx! Thanks for the PR and sorry for the delay. We've been focussing mainly on the site and videos so we haven't had as much time to think about the direction of the web framework. @mbrandonw and I have discussed the future of the CSS API and how we may wanna rethink some core things, but just haven't found the time to do so.

I like how the array literal stuff looks! We need to check out the branch and run some tests to make sure it doesn't cause any performance or type-checking issues. Our stuff can already put the compiler in a spot where it doesn't deliver the most helpful error messages, and I've seen `ExpressibleByArrayLiteral` turn decipherable errors into indecipherable errors, so we wanna be a little careful here.

**Comment by gmosx** [comment]
OK, that's reasonable. I will have to wait and see what you will come up with.

**Comment by stephencelis** [comment]
@gmosx Been a few years :)

I think given that swift-web is still mostly an experimental project (with its dependence on swift-prelude, etc.), we're going to keep things moving slowly and mostly take changes we are intent on using in our projects that depend on it.

We hope to get back to more modern, server-side Swift soon, especially as async/await becomes available on the server! This will give us an opportunity to reconsider our CSS module and make it feel a bit more at home in Swift. We appreciate the discussion, though, and agree that the array expressibility is much nicer than our old reliance on `<>`. Thanks!

**Pull request closed without merging**
